"""empty message

Revision ID: 15e86737607c
Revises: b82f6a37a9f8
Create Date: 2023-11-10 23:54:22.489296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e86737607c'
down_revision = 'b82f6a37a9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('_password', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=256), nullable=True))
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('_password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
